/*
* This file autogenerated;
*
* DO NOT EDIT
*
* Swagger Petstore
* Version: 1.0.0
*
* Generated by https://github.com/oasgo/oasgo
 */

package client

import (
	"bytes"
	"encoding/json"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)

var _ SwaggerPetstore = new(HTTPSwaggerPetstoreClient)

type (
	SwaggerPetstore interface {
		ListPets(res interface{}, limit *string, fancyQueryArg string) (*http.Response, error)
		CreatePet(res interface{}, body Pet) (*http.Response, error)
		ShowPetById(res interface{}, petId string) (*http.Response, error)
	}

	HTTPSwaggerPetstoreClient struct {
		URL  *url.URL
		HTTP *http.Client
	}

	Pet struct {
		ID     int64      `json:"id"`
		Name   string     `json:"name"`
		Nested *PetNested `json:"nested"`
		Tag    string     `json:"tag"`
	}

	PetNested struct {
		Name       string        `json:"name"`
		Omg        *PetNestedOmg `json:"omg"`
		SecondName int64         `json:"second_name"`
	}

	PetNestedOmg struct {
		VeryOmgType int64 `json:"very_omg_type"`
	}

	Error struct {
		Code    int64  `json:"code"`
		Message string `json:"message"`
	}
)

func NewHTTPSwaggerPetstoreClient(host string) (*HTTPSwaggerPetstoreClient, error) {
	u, err := url.Parse(host)
	if err != nil {
		return nil, err
	}
	return &HTTPSwaggerPetstoreClient{
		URL:  u,
		HTTP: &http.Client{},
	}, nil
}

func (c HTTPSwaggerPetstoreClient) ListPets(res interface{}, limit *string, fancyQueryArg string) (*http.Response, error) {
	u := *c.URL
	u.Path = "/pets"

	u.Path = strings.NewReplacer().Replace(u.Path)

	q := u.Query()
	if limit != nil {
		q.Set("limit", *limit)
	}
	q.Set("fancy_query_arg", fancyQueryArg)

	u.RawQuery = q.Encode()

	request, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}

	resp, err := c.HTTP.Do(request)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if r, ok := res.(*string); ok {
		body, err := ioutil.ReadAll(resp.Body)

		if err != nil {
			return resp, err
		}

		*r = string(body)
		return resp, nil
	}

	if err = json.NewDecoder(resp.Body).Decode(res); err != nil {
		return resp, err
	}

	return resp, nil
}

func (c HTTPSwaggerPetstoreClient) CreatePet(res interface{}, body Pet) (*http.Response, error) {
	u := *c.URL
	u.Path = "/pets"

	bs, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequest("POST", u.String(), bytes.NewBuffer(bs))
	if err != nil {
		return nil, err
	}

	resp, err := c.HTTP.Do(request)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if r, ok := res.(*string); ok {
		body, err := ioutil.ReadAll(resp.Body)

		if err != nil {
			return resp, err
		}

		*r = string(body)
		return resp, nil
	}

	if err = json.NewDecoder(resp.Body).Decode(res); err != nil {
		return resp, err
	}

	return resp, nil
}

func (c HTTPSwaggerPetstoreClient) ShowPetById(res interface{}, petId string) (*http.Response, error) {
	u := *c.URL
	u.Path = "/pets/{petId}"

	u.Path = strings.NewReplacer(
		"{petId}", petId,
	).Replace(u.Path)

	q := u.Query()
	u.RawQuery = q.Encode()

	request, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}

	resp, err := c.HTTP.Do(request)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if r, ok := res.(*string); ok {
		body, err := ioutil.ReadAll(resp.Body)

		if err != nil {
			return resp, err
		}

		*r = string(body)
		return resp, nil
	}

	if err = json.NewDecoder(resp.Body).Decode(res); err != nil {
		return resp, err
	}

	return resp, nil
}
