/*
* This file autogenerated;
*
* DO NOT EDIT
* Generated by https://github.com/oasgo/oasgo
 */

package dto

import "github.com/asaskevich/govalidator"

type (
	Error struct {
		Code    int64  `json:"code" valid:"required"`
		Message string `json:"message" valid:"required"`
	}

	Pet struct {
		Tag    string    `json:"tag"`
		Nested PetNested `json:"nested"`
		Id     int64     `json:"id" valid:"required"`
		Name   string    `json:"name" valid:"required"`
	}

	PetNested struct {
		Omg        PetNestedOmg `json:"omg"`
		Name       string       `json:"name"`
		SecondName int64        `json:"second_name"`
	}

	PetNestedOmg struct {
		VeryOmgType int64 `json:"very_omg_type"`
	}
)

func (r *Error) Validate() (bool, error) {
	return govalidator.ValidateStruct(r)
}

func (r *Pet) Validate() (bool, error) {
	return govalidator.ValidateStruct(r)
}

func (r *PetNested) Validate() (bool, error) {
	return govalidator.ValidateStruct(r)
}

func (r *PetNestedOmg) Validate() (bool, error) {
	return govalidator.ValidateStruct(r)
}
