/*
* This file autogenerated;
*
* DO NOT EDIT
* Generated by https://github.com/oasgo/oasgo
 */

package mypacakge

import "net/http"

type (
	CreatePetBody struct {
		Id     int64
		Name   string
		Tag    string
		Nested CreatePetBodyNested
	}

	CreatePetBodyNested struct {
		Omg        CreatePetBodyNestedOmg
		Name       string
		SecondName int64
	}

	CreatePetBodyNestedOmg struct {
		VeryOmgType int64
	}

	Error struct {
		Code    int64
		Message string
	}

	Pet struct {
		Nested PetNested
		Id     int64
		Name   string
		Tag    string
	}

	PetNested struct {
		Name       string
		SecondName int64
		Omg        PetNestedOmg
	}

	PetNestedOmg struct {
		VeryOmgType int64
	}
)

func ListPets(r *http.Request) (limit string, fancyQueryArg string) {

}
func CreatePet(r *http.Request) (body CreatePetBody) {

}
func ShowPetById(r *http.Request) (petId string) {

}
